General cleanup and preparation for Travis deployment
intelsdi-x/snap-plugin-collector-diamond pull request #10
Opened 2017-08-02 12:18 UTC by kdembler

Summary of changes:

- Removed files needed for PyPI - plugin is an application, not a library and isn't meant to be distributed by PyPI - instead, releases will be automated with Travis and pushed to GitHub
- General cleanup

2017-08-02 13:39 UTC, mkleina requested changes

2017-08-02 13:39 UTC, mkleina commented on MANIFEST.in
> -include versioneer.py
This file was autogenerated by `versioneer` command and contains list of files for source distribution:
https://docs.python.org/2/distutils/sourcedist.html

We should discuss whether this file is needed or not.

2017-08-02 13:39 UTC, mkleina commented on setup.cfg
> -[versioneer]
This file is used by `versioneer` command. It should not be removed if user will want to upgrade versioneer related files.

2017-08-02 13:39 UTC, mkleina commented on setup.py
> -# -*- coding: utf-8 -*-
This file is needed by `make pkg` command:
```bash
_info "virtual environment: installing plugin package"
$PYTHON_ENV/bin/pip install -I ${__proj_dir}
```

without this file, ACI package generation is impossible.

2017-08-02 14:34 UTC, kdembler commented on setup.py
> -# -*- coding: utf-8 -*-
You're right, I missed that. Changed PR to WIP, will fix this.

2017-08-08 13:29 UTC, kdembler commented
Following some discussion, approach from PR description is no longer accurate. We decided to  deploy Python plugins to PyPI to give user additional installation option.

2017-08-08 14:15 UTC, mkleina approved these changes

2017-08-09 08:33 UTC, merged